version: '2'
services:
  web:
    build: .
    command: node server.js
    volumes:
      - .:/usr/app/
    ports:
      - "77:00"
    networks:
      - backbone

networks:
    backbone:
        driver: bridge
